spring:
  flyaway:
    baseline-version: '0'
    password: password
    baseline-description: '"init"'
    user: root
    enabled: 'true'
    baseline-on-migrate: 'true'
  application:
    name: Coaching_Center_monolithic
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: 'true'
    properties:
      hibernate:
        default_schema: coaching_center_springboot_monolithic
        format_sql: 'true'
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/coaching_center_springboot_monolithic?useSSL=false
    username: root
    password: password