spring:
  flyaway:
    baseline-version: '0'
    password: root
    baseline-description: '"init"'
    user: admin
    enabled: 'true'
    baseline-on-migrate: 'true'
  application:
    name: Coaching_Center_monolithic
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
    properties:
      hibernate:
        default_schema: coaching_center_springboot_monolithic
        format_sql: 'true'
  datasource:
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    url: jdbc:mysql://localhost:3306/coaching_center_springboot_monolithic
